Adding README and improved the action to update it

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,6 +1,14 @@
 name: Executable size checker
 
-on: [push]
+on:
+  push:
+    paths-ignore:
+      - 'README.md'
+      - 'LICENSE'
+      - '.gitignore'
+
+permissions:
+  contents: write
 
 jobs:
   build:
@@ -19,22 +27,34 @@ jobs:
         run: sudo apt-get install -y upx
 
       - name: Compile the program
-        run: gcc -Os -s -ffunction-sections -fdata-sections -flto -Wl,--gc-sections,-flto ./**.c -lm -lX11 -lGL -ldl -I./include -o zoom
+        run: |
+          set -e
+          gcc -Os -s -ffunction-sections -fdata-sections -flto -Wl,--gc-sections,-flto ./**.c -lm -lX11 -lGL -ldl -I./include -o zoom
 
-      - name: Check executable size
+      - name: Check executable size and update README
         run: |
           size=$(stat -c %s zoom)
           echo "Executable size: $size bytes"
           if [ $size -gt 65536 ]; then
-              echo "The executable size is greater than 64KB"
-              echo "Compressing with UPX..."
-              upx --best zoom
-              size=$(stat -c %s zoom)
-              echo "New executable size: $size bytes"
-              if [ $size -gt 65536 ]; then
-                  echo "Error: The executable size is still greater than 64KB after compression."
-                  exit 1
-              fi
+            echo "The executable size is greater than 64KB"
+            echo "Compressing with UPX..."
+            upx --best zoom
+            size=$(stat -c %s zoom)
+            echo "New executable size: $size bytes"
+            if [ $size -gt 65536 ]; then
+              echo "Error: The executable size is still greater than 64KB after compression."
+              exit 1
+            else
+              sed -i "s/Current executable size: .*/Current executable size: $size bytes (using UPX)/" README.md
+            fi
           else
-          	echo "The executable size is less than or equal to 64KB"
+            sed -i "s/Current executable size: .*\s*(using UPX)*/Current executable size: $size bytes/" README.md
           fi
+
+      - name: Commit and push if changed
+        run: |
+          git config --local user.email "action@github.com"
+          git config --local user.name "GitHub Action"
+          git add README.md
+          git commit -m "Update README with executable size" -a || echo "No changes to commit"
+          git push
